### ISSUE TITLE
Missing docs on how to use

### ISSUE THREAD

**Issue by jandreaucodes** [gssbzn/keo-bot#1]
I've got the bot running on Heroku, but can't figure out (since there's no docs) on how to use it.

I tried deciphering the code, but I can't figure out how to actually give kudos to someone, or get a current list of scores.

Can you offer some guidance on how to interact with the bot?

**Comment by gssbzn** [comment]
Hi @mikeatdesk this was a little game we had in the office and documentation is poor, sorry

If you are not I'll recomend to use this commit 5b3383bb0b8e45aab4f649c26a8ac9a0f87c1817 for heroku, latests version was a rewrite to try to make it more readable and to run on openshift and I think is not usable

Here is the list of commands
https://github.com/gssbzn/kudos-bot/blob/heroku/locales/en.json

And the **keyword** for the kudos can be configured with and ENV var
And would be replaced within thos commands

Let me know if that helps you

**Comment by jandreaucodes** [comment]
Sorry, I still don't get it.

`%s to %s` I assume means "KUDOS_KEYWORD to @slackuser, right?

That doesn't work in my testing though.

If I @the-bots-name with "KUDOS_KEYWORD to @slackuser", it just returns KUDOS_KEYWORD list

Do you mind elaborating a bit on it? I'm sure I'm missing something simple.

**Comment by gssbzn** [comment]
I did a little testing (local) and here's an example

![download](https://cloud.githubusercontent.com/assets/461027/23308099/e546ca48-faa1-11e6-9006-73598d5f5f4b.png)

May use that screenshot for a a better documentation

**Comment by gssbzn** [comment]
If it helps these are my envs
```
TOKEN=xoxb-XXXXXXXXX
KUDOS_WORD=kudos
LOCALE=en
```

**Comment by jandreaucodes** [comment]
Aha. It doesn't work at all without the local set.

That's what I was missing.

Thanks. Will play with this some more and maybe expand it!

**Comment by gssbzn** [comment]
@mikeatdesk did some small refactors to the index file, I still need to work on the mess that the bot is may do some on that on the weekend and and some documentation, and PR is welcome
